### ISSUE TITLE
1.20.1 World Corruption

### ISSUE THREAD

**Issue by kittywitch** [VsnGamer/ElevatorMod#133]
Hi! I have a schematic that once included in a world with my modpack makes the world unable to load on either SMP or SP due to a deadlock in the elevator mod.

Removing the elevator mod fixes this. Therefore, I have determined your mod is at fault for corrupting my world. Adding this schematic to a backup of my world recreates the problem. To use the .construction, remove the .txt and load it into a world with Amulet.

[awoo.construction.txt](https://github.com/user-attachments/files/17382049/awoo.construction.txt)

The modpack in question is within: https://github.com/kittywitch/minecraft-modpack

Here is a relevant log area:
```
"Worker-Main-2" daemon prio=4 Id=115 WAITING on java.util.concurrent.CompletableFuture$Signaller@405f5b37
	at java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CompletableFuture$Signaller@405f5b37
	at java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.compensatedBlock(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.getChunkOffThread(ServerChunkCache.java:3176)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:3141)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6522_(Level.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46865_(Level.java:4041)
	at TRANSFORMER/forge@47.3.10/net.minecraftforge.common.extensions.IForgeBlockGetter.getExistingBlockEntity(IForgeBlockGetter.java:39)
	at TRANSFORMER/elevatorid@1.20.1-1.9/xyz.vsngamer.elevatorid.blocks.ElevatorBlock.getElevatorTile(ElevatorBlock.java:302)
	at TRANSFORMER/elevatorid@1.20.1-1.9/xyz.vsngamer.elevatorid.blocks.ElevatorBlock.m_7753_(ElevatorBlock.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60739_(BlockBehaviour.java:551)
	at TRANSFORMER/starlight@1.1.2+forge.1cda73c/ca.spottedleaf.starlight.common.light.SkyStarLightEngine.tryPropagateSkylight(SkyStarLightEngine.java:673)
	at TRANSFORMER/starlight@1.1.2+forge.1cda73c/ca.spottedleaf.starlight.common.light.SkyStarLightEngine.lightChunk(SkyStarLightEngine.java:547)
	at TRANSFORMER/starlight@1.1.2+forge.1cda73c/ca.spottedleaf.starlight.common.light.StarLightEngine.light(StarLightEngine.java:909)
	at TRANSFORMER/starlight@1.1.2+forge.1cda73c/ca.spottedleaf.starlight.common.light.StarLightInterface.lightChunk(StarLightInterface.java:435)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ThreadedLevelLightEngine.mdfd426d$lambda$lightChunk$5$2(ThreadedLevelLightEngine.java:700)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ThreadedLevelLightEngine$$Lambda/0x000001e4d34a51a8.get(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at TRANSFORMER/starlight@1.1.2+forge.1cda73c/ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:537)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(LevelLightEngine.java:599)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(ThreadedLevelLightEngine.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(ThreadedLevelLightEngine.java:166)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ThreadedLevelLightEngine$$Lambda/0x000001e4d34a5ec0.run(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base@21.0.4/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

"Worker-Main-3" daemon prio=4 Id=116 TIMED_WAITING on java.util.concurrent.ForkJoinPool@3ce7354f
	at java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@3ce7354f
	at java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkUntil(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base@21.0.4/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by kittywitch** [comment]
This would also occur without Starlight, by the way.

**Comment by VsnGamer** [comment]
Hello!

Can you check if it still happens with version [1.20.1-lex-1.9](https://legacy.curseforge.com/minecraft/mc-mods/openblocks-elevator/files/4837768)?
