### ISSUE TITLE
Dedicated Server Crash ElevatorMod-1.12.2-1.3.7

### ISSUE THREAD

**Issue by SteveKnowless** [VsnGamer/ElevatorMod#29]
Latest Update crashes Dedicated Server on Startup

ElevatorMod-1.12.2-1.3.7.jar

```
---- Minecraft Crash Report ----
// My bad.

Time: 2019-02-21 17:04:59 EST
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: xyz.vsngamer.elevator.ElevatorMod$ServerProxy
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:102)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:598)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: xyz.vsngamer.elevator.ElevatorMod$ServerProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
    ... 31 more
Caused by: java.lang.NullPointerException
```

**Comment by Wissi** [comment]
Same issue. Crash on dedicated server:    (using latest ElevatorMod-1.12.2-1.3.7.jar)
`net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: xyz.vsngamer.elevator.ElevatorMod$ServerProxy`

Full crash log [here](https://gist.github.com/Wissi/33e78e4389ce52097fc0da3c1dee2eb4)

**Comment by Chr0n4s** [comment]
same for me

**Comment by VsnGamer** [comment]
I see the problem, will fix probably today

**Comment by VsnGamer** [comment]
Please confirm fix on your end.

**Comment by Chr0n4s** [comment]
fix works for me. ty gj

**Comment by Wissi** [comment]
No more server crash with ElevatorMod-1.12.2-1.3.7.jar
Thank you for quick fix.
